AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "*.gemspec"
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ClassLength:
  Max: 500
Metrics/MethodLength:
  Max: 100
Metrics/ParameterLists:
  Max: 7
Metrics/PerceivedComplexity:
  Max: 15
Style/ConditionalAssignment:
  Enabled: false
