AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "*.gemspec"
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 7
Metrics/PerceivedComplexity:
  Max: 25
Layout/LineLength:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
